name: Validation

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  type-check:
    name: Type Check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: ">=22.0.0"
      - name: Install dependencies
        run: yarn install
      - name: Run type-check
        run: yarn type-check

  lint:
    name: ESLint
    needs: type-check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v4
        with:
          node-version: ">=22.0.0"
      - name: Install dependencies
        run: yarn install
      - name: Run eslint
        run: yarn lint

  test:
    name: Jest Tests
    needs: type-check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: ">=22.0.0"
      - name: Install dependencies
        run: yarn install
      - name: Run jest tests
        run: yarn test

  e2e:
    name: Playwright E2E Tests
    needs: [lint, test]
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:16
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: inspect
        ports:
          - 5432:5432
        options: >-
          --health-cmd "pg_isready -U postgres -d inspect"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    env:
      DATABASE_USER: postgres
      DATABASE_PASSWORD: postgres
      DATABASE_HOST: localhost
      DATABASE_PORT: 5432
      DATABASE_NAME: inspect
      CI: true
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: ">=22.0.0"
      - name: Install dependencies
        run: yarn install
      - name: Install Playwright Browsers
        run: npx playwright install --with-deps
      - name: Build Next.js app
        run: yarn build-prod
      - name: Apply Postgres schema
        run: yarn db:schema
      - name: Seed e2e databases
        run: yarn db:seed-e2e
      - name: Run Playwright tests
        run: yarn e2e
